[project]
name = "blue-archive-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pywikibot>=10.2.0",
    "wikitextparser>=0.56.4",
    "xxhash>=3.5.0",
]
